;;; test-ps-info-triage.el --- ERT tests for ps-info-triage -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'org)
(add-to-list 'load-path "lisp")
(require 'ps-info-triage)

(defconst ps/info-triage-test--queue
  "#+TITLE: Info triage inbox
#+SUBTITLE: 3 items, oldest 1 day — generated by sync.sh, do not edit
#+STARTUP: showall
# Reading this as an agent? Stop — read triage.md in this directory instead.

* 2026-08-14

** 1 · [[file:2026-08-14_146/index.md][Scalable Keyword Spotting via Modular Network Expansion]]  :paper:
   /read before the Friday review/
   [[file:2026-08-14_146/][directory]] · [[https://arxiv.org/abs/2607.19918][source]]

* 2026-08-16

** 2 · [[file:2026-08-16_156/index.md][. (@marlidiuret) • Instagram photos and videos]]
   [[file:2026-08-16_156/][directory]] · [[https://www.instagram.com/marlidiuret/][source]]
** 3 · [[file:2026-08-16_165/index.md][Ever noticed the colored tags on the ancient trees…]]  :post:
   [[file:2026-08-16_165/][directory]]
"
  "A queue in exactly the shape `render_org' (info_triage/sync.py) emits.
Days at level one, items at level two, numbering global across the days.
Includes the cases that broke earlier readers: an item with an intent line
between the heading and the links, one whose heading carries no kind tag at
all, one with no source link, and a last item of a day followed by the next
day rather than by another item.")

(defmacro ps/info-triage-test--in-queue (&rest body)
  "Run BODY in an Org buffer holding the sample queue."
  (declare (indent 0))
  `(with-temp-buffer
     (insert ps/info-triage-test--queue)
     (let ((org-mode-hook nil))
       (org-mode))
     (goto-char (point-min))
     ,@body))

(defun ps/info-triage-test--goto (number)
  "Move point onto the heading of item NUMBER."
  (goto-char (point-min))
  (re-search-forward (format "^\\*\\* %d " number))
  (beginning-of-line))

;;; -------------------------------------------------------
;;; Reading the item at point
;;; -------------------------------------------------------

(ert-deftest ps/info-triage--item-directory-reads-the-directory-link ()
  "The `directory' link is the only place the item's id still appears now that
the property drawer is gone, so this parse is a contract with the generator."
  (ps/info-triage-test--in-queue
    (ps/info-triage-test--goto 1)
    (should (equal (ps/info-triage--item-directory) "2026-08-14_146"))
    (ps/info-triage-test--goto 3)
    (should (equal (ps/info-triage--item-directory) "2026-08-16_165"))))

(ert-deftest ps/info-triage--item-directory-is-not-fooled-by-the-next-item ()
  "An item whose own links are missing must report nothing rather than the
directory of the item below it -- which is what a drop would then delete."
  (with-temp-buffer
    (insert "* 2026-08-14\n\n"
            "** 1 · No links here\n"
            "** 2 · The next one\n"
            "   [[file:2026-08-14_152/][directory]]\n")
    (let ((org-mode-hook nil)) (org-mode))
    (ps/info-triage-test--goto 1)
    (should-not (ps/info-triage--item-directory))))

(ert-deftest ps/info-triage--item-directory-stops-at-the-next-day ()
  "The last item of a day is followed by a *day* heading, not another item, so
bounding the search on the item pattern alone would read past it into the
first item of the next day -- and a drop would delete that one instead."
  (with-temp-buffer
    (insert "* 2026-08-14\n\n"
            "** 1 · No links here\n\n"
            "* 2026-08-15\n\n"
            "** 2 · The next day's first\n"
            "   [[file:2026-08-15_152/][directory]]\n")
    (let ((org-mode-hook nil)) (org-mode))
    (ps/info-triage-test--goto 1)
    (should-not (ps/info-triage--item-directory))))

(ert-deftest ps/info-triage--item-directory-refuses-on-a-day-heading ()
  "A day is not an item; `d' there has nothing to delete."
  (ps/info-triage-test--in-queue
    (re-search-forward "^\\* 2026-08-16")
    (beginning-of-line)
    (should-not (ps/info-triage--item-number))
    (should-not (ps/info-triage--item-directory))))

(ert-deftest ps/info-triage--item-directory-works-from-inside-the-item ()
  "Point lands on the link line as often as on the heading."
  (ps/info-triage-test--in-queue
    (ps/info-triage-test--goto 1)
    (forward-line 1)
    (should (equal (ps/info-triage--item-directory) "2026-08-14_146"))))

(ert-deftest ps/info-triage--item-number-reads-the-heading ()
  "The number is what gets quoted to a routing agent, so it has to be exact."
  (ps/info-triage-test--in-queue
    (ps/info-triage-test--goto 2)
    (should (equal (ps/info-triage--item-number) "2"))))

(ert-deftest ps/info-triage--item-number-copes-with-a-heading-that-has-no-kind ()
  "Item 2 in the sample is the degenerate case: nothing was extracted, so the
heading carries no kind tag at all."
  (ps/info-triage-test--in-queue
    (ps/info-triage-test--goto 2)
    (should (equal (ps/info-triage--item-directory) "2026-08-16_156"))))

(ert-deftest ps/info-triage-next-item-steps-over-the-day-headings ()
  "`n' and `p' walk items.  A day heading is a heading, so stepping by heading
would stop where none of the single keys mean anything."
  (ps/info-triage-test--in-queue
    (ps/info-triage-test--goto 1)
    (ps/info-triage-next-item)
    (should (equal (ps/info-triage--item-number) "2"))
    (ps/info-triage-next-item)
    (should (equal (ps/info-triage--item-number) "3"))
    (ps/info-triage-previous-item)
    (should (equal (ps/info-triage--item-number) "2"))
    (ps/info-triage-previous-item)
    (should (equal (ps/info-triage--item-number) "1"))))

(ert-deftest ps/info-triage-move-item-stays-put-at-either-end ()
  "Running off the end must leave point on the item it was on, not on the
header or the last link line, where `d' would report a different item."
  (ps/info-triage-test--in-queue
    (ps/info-triage-test--goto 1)
    (should-not (ps/info-triage--move-item -1))
    (should (equal (ps/info-triage--item-number) "1"))
    (ps/info-triage-test--goto 3)
    (should-not (ps/info-triage--move-item 1))
    (should (equal (ps/info-triage--item-number) "3"))))

(ert-deftest ps/info-triage--item-path-refuses-above-the-first-item ()
  "Point in the file header is not point on an item, and a drop there would
otherwise be a delete of something unnamed."
  (ps/info-triage-test--in-queue
    (goto-char (point-min))
    (should-error (ps/info-triage--item-path) :type 'user-error)))

(ert-deftest ps/info-triage--item-label-drops-what-the-prompt-already-says ()
  "A confirmation that repeats the number and reads Org markup back at you is
one you stop reading, which is the opposite of what a delete prompt is for."
  (ps/info-triage-test--in-queue
    (ps/info-triage-test--goto 3)
    (should (equal (ps/info-triage--item-label)
                   "Ever noticed the colored tags on the ancient trees…"))
    (ps/info-triage-test--goto 1)
    (should (equal (ps/info-triage--item-label)
                   "Scalable Keyword Spotting via Modular Network Expansion"))))

;;; -------------------------------------------------------
;;; Availability -- what the menu is gated on
;;; -------------------------------------------------------

(ert-deftest ps/info-triage-available-p-follows-the-directory ()
  "The feature is hidden entirely on a machine without the inbox: this config
is shared, and a menu for a tool you do not have is noise."
  (let ((ps/info-triage-directory temporary-file-directory))
    (should (ps/info-triage-available-p)))
  (let ((ps/info-triage-directory "/nowhere/at/all/"))
    (should-not (ps/info-triage-available-p))))

;; `ps/info-triage-sync-script' is bound to nil explicitly: a machine-local
;; setting would otherwise decide the result.
(ert-deftest ps/info-triage-available-p-accepts-a-sync-script-alone ()
  "The first sync is what creates the inbox, so requiring the inbox would hide
the only command able to make it."
  (let ((ps/info-triage-directory "/nowhere/at/all/"))
    (let ((ps/info-triage-sync-script nil))
      (should-not (ps/info-triage-available-p)))
    (let ((ps/info-triage-sync-script "/somewhere/sync.sh"))
      (should (ps/info-triage-available-p)))))

(ert-deftest ps/info-triage-queue-buffer-p-matches-only-the-generated-queue ()
  (let* ((inbox (make-temp-file "ps-triage-test-" :directory))
         (ps/info-triage-directory (file-name-as-directory inbox))
         (queue (expand-file-name "triage.org" inbox))
         (other (expand-file-name "notes.org" inbox)))
    (unwind-protect
        (progn
          (write-region ps/info-triage-test--queue nil queue nil 'silent)
          (write-region "* a plan\n" nil other nil 'silent)
          (let ((queue-buffer (find-file-noselect queue))
                (other-buffer (find-file-noselect other)))
            (unwind-protect
                (progn
                  (should (ps/info-triage-queue-buffer-p queue-buffer))
                  (should-not (ps/info-triage-queue-buffer-p other-buffer)))
              (kill-buffer queue-buffer)
              (kill-buffer other-buffer))))
      (delete-directory inbox :recursive))))

(ert-deftest ps/info-triage-open-refuses-when-there-is-no-inbox ()
  (let ((ps/info-triage-directory "/nowhere/at/all/"))
    (should-error (ps/info-triage-open) :type 'user-error)))

;;; -------------------------------------------------------
;;; Sync status -- read out of the script's own output
;;; -------------------------------------------------------

(ert-deftest ps/info-triage--parse-progress-reads-a-stage-line ()
  (should (equal (ps/info-triage--parse-progress
                  "==> Downloading new and edited items")
                 '(:stage "Downloading new and edited items"))))

(ert-deftest ps/info-triage--parse-progress-cuts-a-stage-at-its-commentary ()
  "The rest of such a line is for someone reading the whole log."
  (should (equal (ps/info-triage--parse-progress
                  "==> Looking for possible neighbours of 5 items — the queue above is ready now")
                 '(:stage "Looking for possible neighbours of 5 items"))))

(ert-deftest ps/info-triage--parse-progress-reads-a-counted-line ()
  "`_progress' pads the count to the width of the total."
  (should (equal (ps/info-triage--parse-progress "    [3/12] 2026-08-14_146")
                 '(:done 3 :total 12)))
  (should (equal (ps/info-triage--parse-progress "    [ 3/12] 2026-08-14_146")
                 '(:done 3 :total 12))))

(ert-deftest ps/info-triage--parse-progress-ignores-everything-else ()
  (should-not (ps/info-triage--parse-progress "Removed processed item: info/x revision 2"))
  (should-not (ps/info-triage--parse-progress "    a label with no count"))
  (should-not (ps/info-triage--parse-progress "")))

(ert-deftest ps/info-triage--status-after-line-starts-each-stage-at-no-count ()
  "A count left over from the stage before would be a lie about this one."
  (let* ((status '(:state running :action sync))
         (status (ps/info-triage--status-after-line status "==> First"))
         (status (ps/info-triage--status-after-line status "    [2/5] x")))
    (should (equal (plist-get status :stage) "First"))
    (should (equal (plist-get status :done) 2))
    (should (equal (plist-get status :total) 5))
    (let ((next (ps/info-triage--status-after-line status "==> Second")))
      (should (equal (plist-get next :stage) "Second"))
      (should-not (plist-get next :total))
      (should (eq (plist-get next :action) 'sync)))
    (should (eq (ps/info-triage--status-after-line status "noise") status))))

(ert-deftest ps/info-triage--status-label-in-full ()
  (should-not (ps/info-triage--status-label '(:state idle)))
  (should (equal (ps/info-triage--status-label '(:state running :action sync))
                 "Syncing"))
  (should (equal (ps/info-triage--status-label
                  '(:state running :action sync :stage "Downloading" :done 3 :total 12))
                 "Syncing · Downloading · 3/12"))
  (should (equal (ps/info-triage--status-label
                  '(:state failed :action sync :detail "it broke"))
                 "Sync failed · it broke"))
  (let ((now (current-time)))
    (should (equal (ps/info-triage--status-label
                    (list :state 'done :action 'sync :finished now :new 3))
                   (concat "Synced " (format-time-string "%H:%M" now) " · 3 new")))
    (should (equal (ps/info-triage--status-label
                    (list :state 'done :action 'sync :finished now :new 0))
                   (concat "Synced " (format-time-string "%H:%M" now) " · nothing new")))
    (should (equal (ps/info-triage--status-label
                    (list :state 'done :action 'regenerate :finished now :new 0))
                   (concat "Rebuilt " (format-time-string "%H:%M" now))))))

(ert-deftest ps/info-triage--status-label-compact-says-only-what-is-news ()
  "The file tree's mode line is narrow, and a marker that is always there
stops being read."
  (should-not (ps/info-triage--status-label '(:state idle) t))
  (should (equal (ps/info-triage--status-label
                  '(:state running :action sync :stage "Downloading" :done 3 :total 12) t)
                 "⇣"))
  (should (equal (ps/info-triage--status-label '(:state failed :detail "x") t) "⇣!"))
  (should (equal (ps/info-triage--status-label '(:state done :new 3) t) "⇣3"))
  (should-not (ps/info-triage--status-label '(:state done :new 0) t))
  (should-not (ps/info-triage--status-label '(:state done :new 3 :seen t) t)))

(ert-deftest ps/info-triage--mark-seen-clears-the-new-items-marker ()
  (let ((ps/info-triage--status (list :state 'done :action 'sync :new 2)))
    (should (ps/info-triage--modeline))
    (ps/info-triage--mark-seen)
    (should-not (ps/info-triage--modeline)))
  ;; A failure is not something looking at the queue resolves.
  (let ((ps/info-triage--status (list :state 'failed :detail "x")))
    (ps/info-triage--mark-seen)
    (should (ps/info-triage--modeline))))

(ert-deftest ps/info-triage--failure-hint-names-the-macos-permission ()
  "The script's ssh is attributed to Emacs, so the same command that works in
a terminal fails here until Emacs is granted Local Network access."
  (let ((output "==> Reading server item revisions
ssh: connect to host 192.168.1.234 port 22: No route to host
Command '['ssh', 'nas', 'test -d /x']' returned non-zero exit status 255.\n"))
    (should (string-match-p "Local Network"
                            (ps/info-triage--failure-hint output 'darwin)))
    (should-not (ps/info-triage--failure-hint output 'gnu/linux))
    (should-not (ps/info-triage--failure-hint "Permission denied" 'darwin))))

(ert-deftest ps/info-triage--failure-detail-falls-back-to-the-last-line ()
  (should (equal (ps/info-triage--failure-detail "==> Stage\nfirst\n  the reason  \n\n")
                 "the reason"))
  (should (equal (ps/info-triage--failure-detail "") "no output")))

(ert-deftest ps/info-triage--header-line-escapes-percent-signs ()
  "The failure line is the script's own text and the header line is a
mode-line construct."
  (let ((ps/info-triage--status '(:state failed :action sync :detail "disk 100% full"))
        (ps/info-triage-directory "/nowhere/at/all/"))
    (should (string-match-p "100%% full" (ps/info-triage--header-line)))
    (should (string-match-p "Retry" (ps/info-triage--header-line)))))

(ert-deftest ps/info-triage-drop-refuses-while-a-sync-runs ()
  "Renumbering is the same script, so the directory must not go first."
  (ps/info-triage-test--in-queue
    (ps/info-triage-test--goto 1)
    (cl-letf (((symbol-function 'ps/info-triage--busy-p) (lambda () t))
              ((symbol-function 'delete-directory)
               (lambda (&rest _) (error "Deleted anyway"))))
      (should-error (ps/info-triage-drop) :type 'user-error))))

;;; -------------------------------------------------------
;;; The queue buffer
;;; -------------------------------------------------------

(ert-deftest ps/info-triage-mode-puts-the-sync-status-on-the-header-line ()
  (ps/info-triage-test--in-queue
    (ps/info-triage-mode 1)
    (should header-line-format)
    (ps/info-triage-mode -1)
    (should-not header-line-format)))

(ert-deftest ps/info-triage-mode-makes-the-queue-read-only ()
  "It is regenerated wholesale on every sync, so anything typed here is lost
-- and saying so is what frees the single-key bindings."
  (ps/info-triage-test--in-queue
    (ps/info-triage-mode 1)
    (should buffer-read-only)
    (ps/info-triage-mode -1)
    (should-not buffer-read-only)))

(ert-deftest ps/info-triage-mode-remaps-org-link-following ()
  "Org puts its own keymap on a link as a text property, which outranks a
minor-mode map -- so only a remap reaches a click on a link.

Both commands must be remapped.  `org-mouse-map' binds mouse-2 to
`org-open-at-mouse', a separate command ending in a plain
`(org-open-at-point)' funcall -- and remapping rewrites dispatch, never a
funcall, so remapping only the second leaves every mouse click going through
stock Org handling and opening the item in another window."
  (ps/info-triage-test--in-queue
    (ps/info-triage-mode 1)
    (should (eq (command-remapping #'org-open-at-point) #'ps/info-triage-follow))
    (should (eq (command-remapping #'org-open-at-mouse)
                #'ps/info-triage-follow-at-mouse))))

;;; test-ps-info-triage.el ends here
