#!/usr/bin/env python3
"""Build a throwaway copy of the sample notes for taking screenshots.

The sample notes in samples/realistic/ carry fixed dates clustered around
ANCHOR (2026-05-21).  Shown on any other day, the agenda is a wall of overdue
items and the schedule view, availability and conflicts -- which read the real
clock -- show an empty day.  This copies the samples out and moves every Org
timestamp by the same number of days, so ANCHOR lands on TODAY and the whole
plan keeps its shape around it.  Weekday names are rewritten to match; times,
ranges and repeaters are kept.  A journal file named by its date moves with it.

The copy also gets the capture-inbox fixture (samples/info-triage/) beside it,
and a neutral name (notes/) because the path shows in the agent's panel.

Nothing here touches the repo: the copy is where Claude Code's edits land
during a screenshot session.

Usage:
    scripts/make_screenshot_vault.py [--dest DIR] [--today YYYY-MM-DD]
    PS_ORG_BASE=<DEST>/notes ./scripts/run_emacs_dev.sh -l "$PWD/scripts/screenshot.el"

See screenshots/README.md for the shot list.
"""

import argparse
import datetime as dt
import os
import re
import shutil
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
ANCHOR = dt.date(2026, 5, 21)
WEEKDAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

# An Org timestamp, active or inactive: the date, then an optional weekday
# name, then whatever follows (time, range, repeater) up to the closing bracket.
# A link's target or description (`[[...]' or `][...]') is never one.
TIMESTAMP = re.compile(
    r"(?<![][])(?P<open>[<\[])(?P<date>\d{4}-\d{2}-\d{2})(?: (?P<day>[A-Za-z]{2,3}))?"
    r"(?P<rest>[^]>\n]*)(?P<close>[]>])")
DATED_NAME = re.compile(r"\d{4}-\d{2}-\d{2}")


def shift_date(text, days):
    """Return the ISO date TEXT moved by DAYS."""
    return (dt.date.fromisoformat(text) + dt.timedelta(days=days)).isoformat()


def shift_timestamps(text, days):
    """Move every Org timestamp in TEXT by DAYS, rewriting its weekday name."""
    def repl(m):
        date = dt.date.fromisoformat(m["date"]) + dt.timedelta(days=days)
        day = f" {WEEKDAYS[date.weekday()]}" if m["day"] else ""
        return f"{m['open']}{date.isoformat()}{day}{m['rest']}{m['close']}"
    return TIMESTAMP.sub(repl, text)


def shift_name(name, days):
    """Move a date in a file NAME (a journal entry) by DAYS."""
    return DATED_NAME.sub(lambda m: shift_date(m[0], days), name)


def build(dest, today):
    days = (today - ANCHOR).days
    notes = dest / "notes"
    if dest.exists():
        shutil.rmtree(dest)
    # .claude/ is regenerated by Emacs when the vault opens.
    shutil.copytree(REPO / "samples/realistic", notes,
                    ignore=shutil.ignore_patterns(".claude"))
    for path in sorted(notes.rglob("*.org")):
        path.write_text(shift_timestamps(path.read_text(), days))
        moved = path.with_name(shift_name(path.name, days))
        if moved != path:
            path.rename(moved)
    fixture = REPO / "samples/info-triage"
    if fixture.is_dir():
        shutil.copytree(fixture, dest / "info-triage-inbox")
    return notes, days


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    p.add_argument("--dest", type=Path,
                   default=Path(os.environ.get("TMPDIR", tempfile.gettempdir()))
                   / "ps-screenshot")
    p.add_argument("--today", type=dt.date.fromisoformat, default=dt.date.today(),
                   help="the day the sample's busiest day should land on")
    args = p.parse_args(argv)
    notes, days = build(args.dest.resolve(), args.today)
    print(f"Sample notes shifted by {days:+d} days: {ANCHOR} -> {args.today}")
    print(f'PS_ORG_BASE={notes} ./scripts/run_emacs_dev.sh -l "$PWD/scripts/screenshot.el"')


if __name__ == "__main__":
    sys.exit(main())
